---
- name: Install elasticsearch # Установка elasticsearch на elastic_server
  hosts: elastic_server
  become: yes
  
  vars_files: ./elk/vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https # Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy elasticsearch # Копирование деб пакета на сервер elasticsearch
      copy:
        src: "{{ elk_source }}/elasticsearch-{{ elk_version }}-amd64.deb"
        dest: "{{ destination }}"

    - name: Install elasticsearch # Установка elasticsearch
      apt:
        deb: "{{ destination }}/elasticsearch-{{ elk_version }}-amd64.deb"

    - name: Copy config file for elasticsearch # Копирование конфига на север эластика
      copy:
        src: ./elk/elasticsearch.yml
        dest: /etc/elasticsearch
        mode: 0660
        owner: root
        group: elasticsearch

    - name: Systemctl daemon reload # Перезагрузка сервиса
      systemd:
        daemon_reload: true
        name: elasticsearch.service
        state: started

    - name: Systemctl enable elasticsearch # Оставить сервис включённым
      systemd:
        name: elasticsearch.service
        state: restarted