---
- name: Install filebeat # Установка filebeat на webservers
  hosts: web_servers
  become: yes
  
  vars_files: ./elk/vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https # Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy filebeat # Копирование деб пакета на сервер filebeat
      copy:
        src: "{{ elk_source }}/filebeat-{{ elk_version }}-amd64.deb"
        dest: "{{ destination }}"

    - name: Install filebeat # Установка filebeat
      apt:
        deb: "{{ destination }}/filebeat-{{ elk_version }}-amd64.deb"

    - name: Copy config file for filebeat # Копирование конфига на север kibana
      copy:
        src: ./elk/filebeat.yml
        dest: /etc/filebeat
        mode: 0600
        owner: root
        group: root

    - name: Systemctl daemon reload filebeat # Перезагрузка демона filebeat
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started

    - name: Restarted nginx # Перезагрузить сервис nginx
      service:
        name: nginx
        state: restarted

    - name: Restarted filebeat # Перезагрузить сервис filebeat
      service:
        name: filebeat.service
        state: restarted

    - name: Systemctl enable filebeat # Оставить включенным постоянно
      ansible.builtin.service:
        name: filebeat.service
        enabled: yes